import React from 'react';
import { Heart, ShieldAlert } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="w-full border-t border-slate-800 bg-slate-950/80 py-8 px-4 mt-16 text-xs text-slate-400">
      <div className="max-w-6xl mx-auto space-y-4 text-center">
        <div className="flex items-center justify-center gap-2 text-slate-300 font-bold text-sm">
          <Heart className="w-4 h-4 text-rose-500 fill-rose-500" />
          <span>CardioHealth AI Clinical Assessment Platform</span>
        </div>

        <div className="max-w-3xl mx-auto p-3 rounded-xl bg-slate-900/60 border border-slate-800 text-slate-400 flex items-center justify-center gap-2">
          <ShieldAlert className="w-4 h-4 text-amber-400 shrink-0" />
          <span>
            <strong>Important Medical Disclaimer:</strong> CardioHealth AI is an educational clinical assessment platform. Predictions generated by this system are for informational purposes only and should not be used as the sole basis for medical decisions. Always consult a licensed healthcare professional.
          </span>
        </div>

        <div className="text-slate-500 text-[11px] space-y-1">
          <div>
            © {new Date().getFullYear()} CardioHealth AI • Rajkot Cardiovascular Sciences Center, Gujarat, India.
          </div>
          <div className="text-slate-400 font-medium">
            Developed by <span className="text-cyan-400 font-semibold">HINDOCHA KARTAVYA KALPESHBHAI</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
